apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app-stock.fullname" . }}
  labels:
    {{- include "app-stock.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "app-stock.selectorLabels" . | nindent 6 }}
  strategy:
    type: {{ .Values.Strategy }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "app-stock.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP